# Generated by Django 4.0.3 on 2022-03-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='candidates',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='candidates',
            name='techskill',
            field=models.CharField(choices=[('Python', 'python'), ('Java', 'java'), ('Ruby', 'ruby'), ('Docker', 'docker'), ('Java Script', 'javascript')], max_length=200, null=True),
        ),
    ]
