# Generated by Django 4.0.3 on 2022-03-19 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortal', '0002_candidates_address_candidates_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidates',
            name='company',
        ),
    ]
