# Generated by Django 4.0.3 on 2022-03-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortal', '0003_remove_candidates_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='company',
            field=models.ManyToManyField(blank=True, to='JobPortal.company'),
        ),
    ]
