# Generated by Django 4.0.3 on 2022-03-19 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortal', '0005_remove_candidates_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='user',
        ),
    ]
