# Generated by Django 4.0.3 on 2022-03-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortal', '0006_remove_company_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='resume',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
